apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/operators/cert-manager/
  - ../../../components/operators/leader-worker-set/
  - ../../../components/operators/rhcl-operator/
