apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/operators/opentelemetry-product/
  - ../../../components/operators/cluster-observability-operator/
