apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kueue-operator
  - job-set-operator
  - leader-worker-set
  - rhcl-operator
  # The following dependencies need a manual configuration
  # - nfd
  # - nvidia-gpu-operator
