{{- if .Values.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: connection-llmisvc.opendatahub.io
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: opendatahub-operator-controller-manager-service
        namespace: {{ include "odh-operator.namespace" . }}
        path: /platform-connection-llmisvc
        port: 443
    failurePolicy: Fail
    name: connection-llmisvc.opendatahub.io
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - llminferenceservices
    sideEffects: NoneOnDryRun
{{- end }}
