{{- if .Values.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: datasciencecluster-v1-defaulter.opendatahub.io
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: opendatahub-operator-controller-manager-service
        namespace: {{ include "odh-operator.namespace" . }}
        path: /mutate-datasciencecluster-v1
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: datasciencecluster-v1-defaulter.opendatahub.io
    rules:
      - apiGroups:
          - datasciencecluster.opendatahub.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - datascienceclusters
    sideEffects: None
{{- end }}
