{{- if .Values.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dscinitialization-v1-validator.opendatahub.io
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: opendatahub-operator-controller-manager-service
        namespace: {{ include "odh-operator.namespace" . }}
        path: /validate-dscinitialization-v1
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: dscinitialization-v1-validator.opendatahub.io
    rules:
      - apiGroups:
          - dscinitialization.opendatahub.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - DELETE
        resources:
          - dscinitializations
    sideEffects: None
{{- end }}
